### ISSUE TITLE
Potion effect issue

### ISSUE THREAD

**Issue by erxson** [Franckyi/IBE-Editor#49]
I tried to unmark show icon and particles options, but it didn't work

**Comment by skyecodes** [comment]
Due to how Minecraft works, in order to make a potion that doesn't show any particles or icon, the process is a bit tricky:
- Set the "Default Potion" to `minecraft:empty`.
- Add the effects you want on your potion using the `+` button, and make sure to uncheck the "Show Particles" and "Show Icon" options for each of these effects.

Please tell me if that works for you.

**Comment by erxson** [comment]
Didn't work. It returns to default checks

**Comment by skyecodes** [comment]
I can't seem to be able to reproduce the issue, so I need more information:
- Which version of the mod are you using?
- Which minecraft version?
- Forge or Fabric?
- Can you also send me the `latest.log` file in your mod folder, just to check if anything shows up.

**Comment by erxson** [comment]
Latest version on modrinth
1.18.1
Fabric
Only this:
[19:15:45] [Render thread/ERROR]: Mod ibeeditor provides a broken implementation of ModMenuApi
java.lang.IllegalArgumentException: Can not set com.terraformersmc.modmenu.gui.widget.DescriptionListWidget field com.terraformersmc.modmenu.gui.ModsScreen.descriptionListWidget to fi.dy.masa.litematica.gui.GuiMainMenu
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.17) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
	at jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
	at com.github.franckyi.ibeeditor.fabric.FabricIBEEditorModMenuApiImpl.lambda$getModConfigScreenFactory$1(FabricIBEEditorModMenuApiImpl.java:35) ~[IBEEditor-1.18.1-2.0.10-fabric.jar:?]
	at com.plusls.MasaGadget.malilib.fastSwitchMasaConfigGui.MasaGuiUtil.lambda$initMasaModScreenList$0(MasaGuiUtil.java:45) ~[MasaGadget.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.plusls.MasaGadget.malilib.fastSwitchMasaConfigGui.MasaGuiUtil.initMasaModScreenList(MasaGuiUtil.java:41) ~[MasaGadget.jar:?]
	at com.plusls.MasaGadget.malilib.fastSwitchMasaConfigGui.MasaGuiUtil.getMasaGuiData(MasaGuiUtil.java:22) ~[MasaGadget.jar:?]
	at fi.dy.masa.malilib.gui.GuiConfigsBase.<init>(GuiConfigsBase.java:39) ~[MaLiLib.jar:?]
	at fi.dy.masa.litematica.gui.GuiConfigs.<init>(GuiConfigs.java:22) ~[Litematica.jar:?]
	at fi.dy.masa.litematica.gui.GuiMainMenu$ButtonListenerChangeMenu.actionPerformedWithButton(GuiMainMenu.java:137) ~[Litematica.jar:?]
	at fi.dy.masa.malilib.gui.button.ButtonBase.onMouseClickedImpl(ButtonBase.java:81) ~[MaLiLib.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:92) ~[MaLiLib.jar:?]
	at fi.dy.masa.malilib.gui.GuiBase.onMouseClicked(GuiBase.java:265) ~[MaLiLib.jar:?]
	at fi.dy.masa.malilib.gui.GuiBase.mouseClicked(GuiBase.java:210) ~[MaLiLib.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:491) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FPSReducer.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:195) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1142) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by erxson** [comment]
hm, in singleplayer, creative world it works

**Comment by erxson** [comment]
(I enabled creative mode on server)

**Comment by erxson** [comment]
I probably did something wrong. I sorry to have disturbed you.
