### ISSUE TITLE
Incompatible with meteor client

### ISSUE THREAD

**Issue by fungoza** [Franckyi/IBE-Editor#74]
IBE Editor crashes when you have saved items in vault
```---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-01-31 00:32:07
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ibeeditor'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.isActive(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null
	at net.minecraft.class_2540.modify$cgb000$xlPackets(class_2540.java:1813)
	at net.minecraft.class_2540.method_10798(class_2540.java:578)
	at com.github.franckyi.ibeeditor.client.Vault.lambda$loadFromFile$0(Vault.java:91)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at com.github.franckyi.ibeeditor.client.Vault.loadFromFile(Vault.java:91)
	at com.github.franckyi.ibeeditor.client.Vault.load(Vault.java:68)
	at com.github.franckyi.ibeeditor.client.ClientInit.setup(ClientInit.java:26)
	at com.github.franckyi.ibeeditor.fabric.FabricIBEEditorModClient.onInitializeClient(FabricIBEEditorModClient.java:21)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more

**Comment by BackslashG** [comment]
boop
