### ISSUE TITLE
A weird error, might have messed up?

### ISSUE THREAD

**Issue by gusDevel0per** [Franckyi/IBE-Editor#89]
As someone who doesn't know how to use this mod, and was trying to give a modded sword a little lore, I saved and closed the sword without finishing it properly, what happened next was the GUI not opening again for the item.

[22:07:55] [Render thread/INFO]: [CHAT] [IBE Editor] An error occured. Please check the logs for more details and report the issue to the mod author.
[22:07:55] [Render thread/ERROR]: Error while rendering GUAPI Scene
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 84 path $.text
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[gson-2.8.9.jar%2336!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at net.minecraft.util.GsonHelper.m_13798_(GsonHelper.java:527) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at net.minecraft.network.chat.Component$Serializer.m_130701_(Component.java:365) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.github.franckyi.ibeeditor.client.screen.model.category.item.ItemDisplayCategoryModel.setupEntries(ItemDisplayCategoryModel.java:32) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.ibeeditor.client.screen.model.category.CategoryModel.initalize(CategoryModel.java:35) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.api.mvc.MVC.createViewAndBind(MVC.java:10) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.api.mvc.SimpleMVC.setup(SimpleMVC.java:17) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.api.GuapiHelper.mvc(GuapiHelper.java:449) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.ibeeditor.client.screen.view.CategoryEntryScreenView.lambda$createEditor$0(CategoryEntryScreenView.java:19) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.delegate.VanillaListViewSkinDelegate.createList(VanillaListViewSkinDelegate.java:16) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.delegate.AbstractVanillaListNodeSkinDelegate.refreshList(AbstractVanillaListNodeSkinDelegate.java:143) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.delegate.AbstractVanillaListNodeSkinDelegate.preRender(AbstractVanillaListNodeSkinDelegate.java:93) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaWidgetSkin.preRender(AbstractVanillaWidgetSkin.java:20) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.node.AbstractNode.preRender(AbstractNode.java:247) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaGroupSkin.preRender(AbstractVanillaGroupSkin.java:13) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaGroupSkin.preRender(AbstractVanillaGroupSkin.java:8) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.node.AbstractNode.preRender(AbstractNode.java:247) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaGroupSkin.preRender(AbstractVanillaGroupSkin.java:13) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaGroupSkin.preRender(AbstractVanillaGroupSkin.java:8) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.node.AbstractNode.preRender(AbstractNode.java:247) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaGroupSkin.preRender(AbstractVanillaGroupSkin.java:13) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.theme.vanilla.AbstractVanillaGroupSkin.preRender(AbstractVanillaGroupSkin.java:8) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.node.AbstractNode.preRender(AbstractNode.java:247) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.node.AbstractScene.m_6305_(AbstractScene.java:150) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.ScreenHandlerImpl.render(ScreenHandlerImpl.java:111) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at com.github.franckyi.guapi.base.ScreenHandlerImpl$GuapiScreen.m_6305_(ScreenHandlerImpl.java:193) ~[IBEEditor-1.18.2-2.2.0-forge.jar%23127!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.2.10-universal.jar%23188!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.2.10-universal.jar%23188!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23183!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 84 path $.text
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:683) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[gson-2.8.9.jar%2336!/:?]
	... 56 more

**Comment by skyecodes** [comment]
Could you try opening the SNBT editor for this item (R key) and paste the item data here?
