### ISSUE TITLE
mod loads once then doesnt work on that profile again

### ISSUE THREAD

**Issue by anthony1204** [Franckyi/IBE-Editor#95]
im on fabric 1.20.4 and it worked yesterday and was amazing but next day, it does not boot without disabling it. it gets to initing configeration on ibe editor then stops. where is this 'configeration' stored?

**Comment by anthony1204** [comment]
minecraft log:

```java
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-03-22 19:38:59
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ibeeditor'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_8911: Loading NBT data
	at net.minecraft.class_2507.method_52892(class_2507.java:190)
	at net.minecraft.class_2507.method_10626(class_2507.java:180)
	at net.minecraft.class_2507.method_10625(class_2507.java:105)
	at net.minecraft.class_2507.method_10627(class_2507.java:101)
	at com.github.franckyi.ibeeditor.client.Vault.safeReadNbt(Vault.java:114)
	at com.github.franckyi.ibeeditor.client.Vault.lambda$loadFromFile$0(Vault.java:92)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.IntPipeline$Head.forEach(Unknown Source)
	at com.github.franckyi.ibeeditor.client.Vault.loadFromFile(Vault.java:92)
	at com.github.franckyi.ibeeditor.client.Vault.load(Vault.java:69)
	at com.github.franckyi.ibeeditor.client.ClientInit.setup(ClientInit.java:26)
	at com.github.franckyi.ibeeditor.fabric.FabricIBEEditorModClient.onInitializeClient(FabricIBEEditorModClient.java:21)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.io.EOFException
	at io.netty.buffer.ByteBufInputStream.readByte(ByteBufInputStream.java:212)
	at net.minecraft.class_2487$1.method_53889(class_2487.java:74)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:63)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:58)
	at net.minecraft.class_2507.method_52892(class_2507.java:185)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (aarch64) version 13.4
	Java Version: 17.0.10, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 231561280 bytes (220 MiB) / 426770432 bytes (407 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 8192.00
	Virtual memory used (MB): 5380.14
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx2048M
	Fabric Mods: 
		bettercommandblockui: BetterCommandBlockUI 0.4.2
		chesttracker: Chest Tracker 2.2.0+1.20.4
			searchables: Searchables 1.0.3
			whereisit: Where Is It 2.3.3+1.20.4
				jackfredlib: JackFredLib 0.9.0+1.20.4
					jackfredlib-base: JackFredLib: Base 1.3.0+1.20.4
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.20.4
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.20.4
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.20.4
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.20.4
					jackfredlib-toasts: JackFredLib: Toasts 1.0.4+1.20.4
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		crash-pipe: Crash Pipe 0.1.0
		craterlib: CraterLib 1.1.0
		entityculling: EntityCulling 1.6.3.1
		fabric-api: Fabric API 0.92.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		ferritecore: FerriteCore 6.0.3
		fzmm: FZMM 0.2.8
			placeholder-api: Placeholder API 2.3.0+1.20.3
		ibeeditor: IBE Editor 2.2.7
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		iris: Iris 1.6.14
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.17.0
		litematica_printer: Litematica Printer 7.1.0
		malilib: MaLiLib 0.18.0
		memoryleakfix: Memory Leak Fix 1.1.5
		meteor-client: Meteor Client 0.5.6-1992
		meteor-rejects: Meteor Rejects 0.3
			seedcrackerx-api: SeedCrackerX API 2.10.1
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		mousetweaks: Mouse Tweaks 2.25
		nomoreadvancement: nomoreadvancement 0.2
		owo: oωo 0.12.0+1.20.3
			blue_endless_jankson: jankson 1.2.2
		replaymod: Replay Mod 1.20.4-2.6.14
		rrls: Remove Reloading Screen 4.0.1+mc1.20.4-fabric
		simplerpc: Simple RPC 3.2.5
		sodium: Sodium 0.5.5
		songplayer: Song Player 3.1.3
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		uiutils: UI Utils 1.4.3
		worldedit: WorldEdit 7.3.0-beta-03+d6d222e
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.20.4
	Launcher name: theseus
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_AU
	CPU: <unknown> (using mac - anthony)
```

**Comment by anthony1204** [comment]
i know why, dont store items in the vault
